spring:
  redis:
    # 集群
    cluster:
      # 集群地址
      nodes:
        redis:7000,redis:7001,redis:7002,redis:7003,redis:7004,redis:7005

    # 连接驱动
    lettuce:
      # 连接池配置
      pool:
        # 最大空闲连接
        max-idle: 8
        # 最大连接数
        max-active: 8
        # 最小空闲连接
        min-idle: 2
        # 最大建立连接等待时间
        max-wait: 1ms

# 自定义的配置，所以idea会爆红
hbase:
  conf:
    confMaps:
      'hbase.zookeeper.quorum' : 'zookeeper'
      'hbase.zookeeper.property.clientPort' : '2181'