sources: ["AppendAcceptedCount","AppendBatchAcceptedCount","AppendBatchReceivedCount","AppendReceivedCount","ChannelWriteFail","EventAcceptedCount","EventReadFail","EventReceivedCount","GenericProcessingFail","KafkaCommitTimer","KafkaEmptyCount","KafkaEventGetTimer","OpenConnectionCount"]
#- AppendAcceptedCount
#  AppendBatchAcceptedCount
#  AppendBatchReceivedCount
#  AppendReceivedCount
#  ChannelWriteFail
#  EventAcceptedCount
#  EventReadFail
#  EventReceivedCount
#  GenericProcessingFail
#  KafkaCommitTimer
#  KafkaEmptyCount
#  KafkaEventGetTimer
#  OpenConnectionCount

channels: ["ChannelCapacity","ChannelSize","CheckpointBackupWriteErrorCount","CheckpointWriteErrorCount","EventPutAttemptCount","EventPutErrorCount","EventPutSuccessCount","EventTakeAttemptCount","EventTakeErrorCount","EventTakeSuccessCount","KafkaCommitTimer","KafkaEventGetTimer","KafkaEventSendTimer","Open","RollbackCounter","Unhealthy","RollbackCount","ChannelFillPercentage"]
#- ChannelCapacity
#  ChannelSize
#  CheckpointBackupWriteErrorCount
#  CheckpointWriteErrorCount
#  EventPutAttemptCount
#  EventPutErrorCount
#  EventPutSuccessCount
#  EventTakeAttemptCount
#  EventTakeErrorCount
#  EventTakeSuccessCount
#  KafkaCommitTimer
#  KafkaEventGetTimer
#  KafkaEventSendTimer
#  Open
#  RollbackCounter
#  Unhealthy

#  ChannelFillPercentage

sinks: ["BatchCompleteCount","BatchEmptyCount","BatchUnderflowCount","ChannelReadFail","ConnectionClosedCount","ConnectionCreatedCount","ConnectionFailedCount","EventDrainAttemptCount","EventDrainSuccessCount","EventWriteFail","KafkaEventSendTimer","RollbackCount"]
#- BatchCompleteCount
#  BatchEmptyCount
#  BatchUnderflowCount
#  ChannelReadFail
#  ConnectionClosedCount
#  ConnectionCreatedCount
#  ConnectionFailedCount
#  EventDrainAttemptCount
#  EventDrainSuccessCount
#  EventWriteFail
#  KafkaEventSendTimer
#  RollbackCount